// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aAVrWby13Whpj9iWc38egj
// Component: hvSQANW1mITtx
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconLink from "../../IconLink"; // plasmic-import: -NTaHgkt01icFA/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: kajc9ujuy5MJcK/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: aAVrWby13Whpj9iWc38egj/projectcss
import * as sty from "./PlasmicFooter.module.css"; // plasmic-import: hvSQANW1mITtx/css
import LocationArrowIcon from "./icons/PlasmicIcon__LocationArrow"; // plasmic-import: UyirsZVcHszZaV/icon
import FacebookIcon from "./icons/PlasmicIcon__Facebook"; // plasmic-import: TzhyxC54rSznIA/icon
import InstagramIcon from "./icons/PlasmicIcon__Instagram"; // plasmic-import: D6NoJXAr9wzJRY/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin"; // plasmic-import: UKmwDziCoffGvA/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__n5Y)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__z0C7)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___4TvsB
            )}
          >
            {"Information"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__wtRM)}
          >
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link___4Gw5T
              )}
              href={"#"}
            >
              {"About Us"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__hceJu
              )}
              href={"#"}
            >
              {"Contact Us"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__zrlK2
              )}
              href={"#"}
            >
              {"News"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__yLqVq
              )}
              href={"#"}
            >
              {"Store"}
            </a>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__h2Bqy)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__q5QHx
            )}
          >
            {"Collections"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__wm6Ts)}
          >
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__apz
              )}
              href={"#"}
            >
              {"Wooden Chair"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__x8BNy
              )}
              href={"#"}
            >
              {"Royal Cloth Sofa"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__rTj5W
              )}
              href={"#"}
            >
              {"Accent Chair"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link___6Kmme
              )}
              href={"#"}
            >
              {"Bed"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__gLp5C
              )}
              href={"#"}
            >
              {"Hanging Lamp"}
            </a>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__fetFf)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__pNwMi
            )}
          >
            {"My Accounts"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__epw9B)}
          >
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link___4UfaN
              )}
              href={"#"}
            >
              {"My Account"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__pfjTp
              )}
              href={"#"}
            >
              {"Wishlist"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__kbe8E
              )}
              href={"#"}
            >
              {"Community"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__g35Pv
              )}
              href={"#"}
            >
              {"Order History"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__swIyn
              )}
              href={"#"}
            >
              {"My Cart"}
            </a>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__oxWwk)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__aUVmU
            )}
          >
            {"Newsletter"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__pWrun
            )}
          >
            {"Subscribe to get latest news, updates, and information"}
          </div>

          <div className={classNames(defaultcss.all, sty.box__cyRyi)}>
            <input
              data-plasmic-name={"textbox"}
              data-plasmic-override={overrides.textbox}
              className={classNames(defaultcss.input, sty.textbox)}
              placeholder={"Enter Email Here..."}
              size={1}
              type={"text"}
              value={""}
            />

            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(defaultcss.button, sty.button)}
            >
              <LocationArrowIcon
                className={classNames(defaultcss.all, sty.svg___7ZxF)}
                role={"img"}
              />
            </button>
          </div>
        </p.Stack>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__kM3I)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__rfLjs)}
        >
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__jh35L)}
            icon={
              <FacebookIcon
                className={classNames(defaultcss.all, sty.svg__q9GRx)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__jgIoM)}
            icon={
              <InstagramIcon
                className={classNames(defaultcss.all, sty.svg__bjPC)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink___0QyYr)}
            icon={
              <LinkedinIcon
                className={classNames(defaultcss.all, sty.svg__qLJiK)}
                role={"img"}
              />
            }
          />
        </p.Stack>

        <div className={classNames(defaultcss.all, sty.box__pCbTc)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__yCdnq
            )}
          >
            {"© Copyright. "}
          </div>

          <a
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link__l6O95
            )}
            href={"https://www.plasmic.app/"}
          >
            {"Made by Plasmic. "}
          </a>

          <a
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link___6ZgjS
            )}
            href={"https://www.themesine.com/"}
          >
            {"Inspired by Themesine."}
          </a>
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textbox", "button"],
  textbox: ["textbox"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textbox: makeNodeComponent("textbox"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
