// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aAVrWby13Whpj9iWc38egj
// Component: m3slDbDW0MwyP
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: e8-nArFwQLZxg/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: jQAcCX9m0JoW-q/component
import ProductCard from "../../ProductCard"; // plasmic-import: 404crsqwWn8dHZ/component
import Ratings from "../../Ratings"; // plasmic-import: Xd1DQoJebZzcVO/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: i6M3Q_4JnzkBN/component
import BlogPost from "../../BlogPost"; // plasmic-import: vmB_qOsfIVq8ca/component
import Footer from "../../Footer"; // plasmic-import: hvSQANW1mITtx/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: kajc9ujuy5MJcK/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: aAVrWby13Whpj9iWc38egj/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: m3slDbDW0MwyP/css
import arrivals1EHBysIztk0G4Tm from "./images/arrivals1.png"; // plasmic-import: eHBysIztk0g4Tm/picture
import arrivals2BIrkuFVmcq3Xyn from "./images/arrivals2.png"; // plasmic-import: BIrkuFVmcq3Xyn/picture
import arrivals30I01Kk43O9EHaM from "./images/arrivals3.png"; // plasmic-import: 0I01KK43o9eHaM/picture
import arrivals4Xkg2OnR7F0E3E from "./images/arrivals4.png"; // plasmic-import: XKG2onR_7F0E3e/picture
import arrivals5Wg1S0C5Ybi40Z from "./images/arrivals5.png"; // plasmic-import: _Wg1S0C5YBI40z/picture
import arrivals6U9IzEeAFnehlix from "./images/arrivals6.png"; // plasmic-import: u9izEeAFnehlix/picture
import arrivals7TEr2IUpkoyN2Q from "./images/arrivals7.png"; // plasmic-import: tEr2_iUpkoyN2Q/picture
import arrivals82EcPzi5ZrgoiMv from "./images/arrivals8.png"; // plasmic-import: 2ecPzi5zrgoiMv/picture
import f2OhLUaQqLeUAeN1 from "./images/f2.jpeg"; // plasmic-import: OhLUaQQLeUAeN1/picture
import f3UGSq0BqU1NXrm from "./images/f3.jpeg"; // plasmic-import: uG_sq0BqU1nXRM/picture
import f4Ta7ZqnxkBKjcxg from "./images/f4.jpeg"; // plasmic-import: ta7ZqnxkBKjcxg/picture
import b1MjjIccZrkZl4Yd from "./images/b1.jpeg"; // plasmic-import: mjjICCZrkZl4yd/picture
import b223CAUlaVgUTf9 from "./images/b2.jpeg"; // plasmic-import: 23cA-UlaVgUTf9/picture
import b337ZnNtSmna8FSh from "./images/b3.jpeg"; // plasmic-import: 37ZnNtSmna8fSh/picture
import adidasRRdzv27LhslL7 from "./images/adidas.png"; // plasmic-import: _RRdzv27lhslL7/picture
import hm7EZjDo9H1Q8Vvu from "./images/hm.png"; // plasmic-import: 7EZjDO9H1q8Vvu/picture
import kappaD9KJpywBbh1Lq2 from "./images/kappa.png"; // plasmic-import: D9kJpywBBH1LQ2/picture
import lacostePeBR7H711DJyq from "./images/lacoste.png"; // plasmic-import: Pe-bR7h711dJYQ/picture
import levisCakjewngLdqnnz from "./images/levis.png"; // plasmic-import: cakjewngLDQNNZ/picture

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__jpg1V)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__lZ63R)}
            >
              <div className={classNames(defaultcss.all, sty.box___0HVez)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box___9GQro)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___2W9Pe
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__xxSmw)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__u5U4J)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__qp26S)}
                    height={120}
                    role={"img"}
                    src={arrivals1EHBysIztk0G4Tm}
                    width={120}
                  />
                }
                onSale={"onSale"}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__pLuo8)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__aekUl)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__q3IrJ)}
                    height={116}
                    role={"img"}
                    src={arrivals2BIrkuFVmcq3Xyn}
                    width={138}
                  />
                }
                onSale={"onSale"}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__izyZz)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__wQiD)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__xmXg)}
                    height={116}
                    role={"img"}
                    src={arrivals30I01Kk43O9EHaM}
                    width={135}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___19D5F
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__pseEo)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__rndQg)}
                    height={130}
                    role={"img"}
                    src={arrivals4Xkg2OnR7F0E3E}
                    width={100}
                  />
                }
                onSale={"onSale"}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__jVzxz)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__nfoAw)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__zegTi)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__mlvM)}
                    height={127}
                    role={"img"}
                    src={arrivals5Wg1S0C5Ybi40Z}
                    width={105}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__xpiL5)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__dbcIk)}
                    height={123}
                    role={"img"}
                    src={arrivals6U9IzEeAFnehlix}
                    width={176}
                  />
                }
                onSale={"onSale"}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__pbayf)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__vwWj)}
                    height={120}
                    role={"img"}
                    src={arrivals7TEr2IUpkoyN2Q}
                    width={160}
                  />
                }
                onSale={"onSale"}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__dsGc4)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__nqd2A)}
                    height={101}
                    role={"img"}
                    src={arrivals82EcPzi5ZrgoiMv}
                    width={191}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__vWPt0
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.box__pugnU)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__hdPyb
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__a67D7)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__uxvGp)}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lePz3
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__lGlHi)}
                    numReviews={"(12 Review)"}
                    stars={"two"}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tdjfT
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__edtsF)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__kIVtU)}
                    height={310}
                    role={"img"}
                    src={f2OhLUaQqLeUAeN1}
                    width={270}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__jomPt)}
                    stars={"four"}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__oajbY)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__f8QvS)}
                    height={310}
                    role={"img"}
                    src={f3UGSq0BqU1NXrm}
                    width={270}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__ttf6C)}
                    numReviews={"(23 Review)"}
                    stars={"five"}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__w0Xdf)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___4NaI)}
                    height={310}
                    role={"img"}
                    src={f4Ta7ZqnxkBKjcxg}
                    width={270}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__ixizR)}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews"}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box__yGeZy)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__ah3Cr
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__mFp9)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__mTqqd)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__z3Iuw)}
                    height={250}
                    role={"img"}
                    src={b1MjjIccZrkZl4Yd}
                    width={370}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__jqXc6)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__mQsj7)}
                    height={250}
                    role={"img"}
                    src={b223CAUlaVgUTf9}
                    width={370}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__in5K1)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ixj)}
                    height={250}
                    role={"img"}
                    src={b337ZnNtSmna8FSh}
                    width={370}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__imbeE)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__c4Pn)}
                height={60}
                role={"img"}
                src={adidasRRdzv27LhslL7}
                width={90}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__qip4B)}
                height={60}
                role={"img"}
                src={hm7EZjDo9H1Q8Vvu}
                width={91}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__jQ0Oy)}
                height={60}
                role={"img"}
                src={kappaD9KJpywBbh1Lq2}
                width={98}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__gXBud)}
                height={60}
                role={"img"}
                src={lacostePeBR7H711DJyq}
                width={124}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__wbBFx)}
                height={60}
                role={"img"}
                src={levisCakjewngLdqnnz}
                width={125}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
