// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aAVrWby13Whpj9iWc38egj
// Component: Xd1DQoJebZzcVO
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: aAVrWby13Whpj9iWc38egj/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: Xd1DQoJebZzcVO/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: DyrIWqmFapRn2O/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__az7It, {
              [sty.svg__stars_five__az7Itzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_zero__az7ItQ2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__fyS46, {
              [sty.svg__stars_five__fyS46Zn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__fyS46KaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__fyS46HmRk1]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__fyS46YcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__fyS46Zipgz]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__fyS46Q2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__e9Gh, {
              [sty.svg__stars_five__e9Ghzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__e9GhKaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__e9GhhmRk1]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__e9GhYcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__e9GhZipgz]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__e9GhQ2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__o3Ouw, {
              [sty.svg__stars_five__o3OuWzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__o3OuwKaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__o3OuWhmRk1]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__o3OuwYcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__o3Ouwzipgz]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__o3Ouwq2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___03B, {
              [sty.svg__stars_five___03BZn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___03BKaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one___03BHmRk1]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three___03BYcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two___03BZipgz]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero___03BQ2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__sxgR3, {
              [sty.svg__stars_five__sxgR3Zn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__sxgR3KaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__sxgR3HmRk1]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__sxgR3YcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__sxgR3Zipgz]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__sxgR3Q2Mk3]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__cGhTz, {
              [sty.svg__stars_five__cGhTzzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__cGhTzKaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three__cGhTzYcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__cGhTzZipgz]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__rnUlg, {
              [sty.svg__stars_five__rnUlgzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__rnUlgKaBg]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three__rnUlgYcC5F]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ezTt2, {
              [sty.svg__stars_five__ezTt2Zn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__ezTt2KaBg]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__uQv7L, {
              [sty.svg__stars_five__uQv7Lzn5XE]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
